### ISSUE TITLE
Cant read the yahoo page

### ISSUE THREAD

**Issue by Denaton** [gregtuc/StockSocket#13]
I am getting this error for each headless page it open.

> Error: Evaluation failed: TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at __puppeteer_evaluation_script__:26:16
    at ExecutionContext._evaluateInternal (Q:\Node\Trader\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:218:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ExecutionContext.evaluate (Q:\Node\Trader\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:107:16)
    at async startDataFeed (Q:\Node\Trader\node_modules\stocksocket\stocksocket.js:76:5)

And my project contains only the code example.

**Comment by gregtuc** [comment]
Hey @Denaton, did you obtain this error after post-market trading ended at (8:00pm ET)? If so, could you try again between 4:00AM to 8:00PM ET to see if you get the same error? 

I suspect this error may occur when the module is used when the market is shut down - if so I'll implement a quick patch with some error handling.

**Comment by chielteuben** [comment]
I think this is an issue specifically for EU users as Yahoo Finance shows a location based consent warning page through a temporary redirect (307) before showing any actual data.

**Comment by gregtuc** [comment]
@chielteuben Running Puppeteer through an EU-based proxy server shows the same thing on my end. Working on a patch for that now

**Comment by gregtuc** [comment]
Addressed issues with now-published version [StockSocket v1.2.0](https://www.npmjs.com/package/stocksocket/v/1.2.0). Will hold off on closing in case any further issues with this come up

**Comment by chielteuben** [comment]
I can confirm that fixed the issue on my end.
