### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by marikiti-project** [gregtuc/StockSocket#18]
Hi Greg, 

Great Work.

How can we add realtime volume updates to this script?

Thanks in advance.

**Comment by gregtuc** [comment]
Hey there! Great idea, I'm actually working on implementing that functionality right now - it's part of an overhaul of the code that gets the price-change data.

Link to the issue (if you want to keep track of progress): https://github.com/gregtuc/StockSocket/issues/19

**Comment by gregtuc** [comment]
After decoding Yahoo's websocket traffic, it seems like no real-time volume information is sent by them. The only real-time stock properties that can be received are as shown below:

![image](https://user-images.githubusercontent.com/60011793/113072074-206af580-9194-11eb-996e-2daf70d46c83.png)

If you need stock volume information, I recommend polling Yahoo with an HTTP GET request - you will get responses containing a JSON object with tons of information about the stock.

URL (switch TSLA for whichever stock you want): https://query1.finance.yahoo.com/v8/finance/chart/TSLA?region=US&lang=en-US&includePrePost=false&interval=2m&useYfid=true&range=1d&corsDomain=finance.yahoo.com&.tsrc=finance

**Comment by marikiti-project** [comment]
Sweet work, 

For some reason i think the live update to the volume information is only available during market hours. 

Will confirm once the market opens but i recall seeing live volume updates. 

Cheers

**Comment by gregtuc** [comment]
@marikiti-project You're right! Volume info sent during market hours. Pic of info at 10am ET:
![image](https://user-images.githubusercontent.com/60011793/113158308-aecd8e80-9209-11eb-82b9-f331a58b9078.png)

Will let you know once the changes are implemented

**Comment by gregtuc** [comment]
changes made and published
