### ISSUE TITLE
Need help regarding starting the file.

### ISSUE THREAD

**Issue by vishvesh098** [gregtuc/StockSocket#26]
Hi, first of all I must thank you for creating such wonderful yahoo live streamer ! I am Vishvesh Upadhyay from India. All the questions below are for NSE (National Stock Exchange) India.

I am very new to programming world ! and almost first time using Node.Js and JS program / module.

I am currently using yahooquery with sqlite3 on google colab I am facing quite an issue regarding timing of the price-volume data.

I need your guidance on how use your StockSocket. (because in python i just pip install -- and run code from Spyder and it gives me the result, I downloaded you repo and create package with npm init and npm install but dont know how to start the actual web streaming !)

1) Can you guide me how to setup it ? (I just need some direction for how to run it and get live streaming data then after I will use it with my python code)

2) I am running a python code which is fetching currently 40 tickers at once in almost 1 to 1.2 seconds. With your code is it possible to stream 40 tickers (or my target 160 tickers) simultaneously and reliably ?

3) If possible i need your views on if connection is dropped or disconnected then is there any mechanism to reconnect it automatically ?

4) Also i need your suggestion for my project. I am creating an stock alert system (then planning to upgrade it to full fledged algo system). My plan is to get data live data from StockSocket -> then feed it to Python - Pandas -> then to Sqlite3 Local database -> fetch multi timeframe OHLCV candle from DB using Pandas -> then running different analysis on them -> create alert system (max time for all tasks is up to 5-7 secs) and then evolve it to full fledged algo system.

Thanks and reply soon !

Regards,
Vishvesh Upadhyay.

**Comment by vishvesh098** [comment]
@gregtuc Hi please help me.

**Comment by vishvesh098** [comment]
@gregtuc hi i recently started it by installing repo into C:\Program Files\nodejs\node_modules and the script works !! is this the correct way to use it ?

Also can you guide me on how to connect output of this livestream to my python code ? I need json output for my code.

Thank you !

**Comment by gregtuc** [comment]
Hi Vishvesh!

### Answering your Questions

1) This is an npm (node package manager) module. I made two [sample directories](https://github.com/gregtuc/scripts) available on my profile. The advanced repository has a larger implementation using React (client-side), and the basic application runs a small express server and just logs the results (Note that you don't need an actual server to run this code, it's just how I typically set up my test scripts). To use sample-stocksocket-basic:
- Clone the repository
- Navigate to the repository in your command line using `cd sample-stocksocket-basic`
- Run `npm install` in your command line
- Run `node index.js`

2) I have run load tests with the module for several hours with 120 tickers with minimal losses in speed. I'm unsure about scaling to 160 tickers, but it's probably fine.

3) The Websocket is designed not to have a timeout set, as in some situations it must continue running with no input for several days (like when the markets are closed over the weekend). That being said, there are plans to implement some redundancy measures in my code in case of a drop/disconnect moving forward. There have been no issues reported with dropped/disconnected connections yet, though. 

4) Sounds like a very cool project man!

### Integrating the module into Python

Now for connecting the output to your Python code, I'm not positive on the best way to do that. I recommend taking a look at this article here: https://www.sohamkamani.com/blog/2015/08/21/python-nodejs-comm/
I'll see if I can rig up an example for you over the weekend :-)

If that doesn't work, the other (probably much slower and less efficient) method that I can think of is having a Node.js server set up that sends the stock data to a Python-based server every time that stock data comes in (via websocket or HTTP stream).

**Comment by vishvesh098** [comment]
@gregtuc Thank you Greg for such awesome response ! I will try running those scripts ! Thank you for your efforts !

On Integrating the module into Python:-

I can not wait to see your example ! Meanwhile I try with sohamkamani.com method.

Thanks & Regards,
Vishvesh

**Comment by gregtuc** [comment]
> I can not wait to see your example ! Meanwhile I try with sohamkamani.com method.
> 
> Thanks & Regards,
> Vishvesh

I won’t be able to find time this week to make an example, sorry! Best of luck with it though.

**Comment by vishvesh098** [comment]
@gregtuc greg no problem ! I am learning the method to integrate node with python. Thank you for the wishes !

**Comment by vishvesh098** [comment]
@gregtuc Hi greg ! can you do me a favor ? If possible can you give me file which gives just id, price, time and volume ? (because in my database I store price, time & volume data in Ticker Specific Tables so it may reduce time on my end)

By doing so will it reduce the workload both on my side as well as on yahoo webstreaming (Considering 160 tickers) ?

I am currently tinkering _finstreamer-proto.js but it is very complex to understand !

**Comment by gregtuc** [comment]
> @gregtuc Hi greg ! can you do me a favor ? If possible can you give me file which gives just id, price, time and volume ? (because in my database I store price, time & volume data in Ticker Specific Tables so it may reduce time on my end)
> 
> By doing so will it reduce the workload both on my side as well as on yahoo webstreaming (Considering 160 tickers) ?
> 
> I am currently tinkering _finstreamer-proto.js but it is very complex to understand !

The data structure is sent from Yahoo servers, I don’t control any of the contents. You could change the protobuf file to only decode specific properties, but I’m not sure it would reduce workload in any significant way.

Hope that helps

**Comment by vishvesh098** [comment]
ok. got it
