### ISSUE TITLE
Sweet client

### ISSUE THREAD

**Issue by brotzky** [gregtuc/StockSocket#31]
Hey, nice socket client! We use yahoo as a fallback data provider.
I lead engineering at [Fey](https://feyapp.com/) and we're looking for engineers (Backend | TS/Node). Wondering if you'd be interested to learn more?

**Comment by gregtuc** [comment]
Hey @brotzky ! I took a peek at your platform and I think that Fey’s mission is really exciting and fills a void. I'm especially curious about the mysterious Phase II. I’d love to hear more!

**Comment by brotzky** [comment]
Email me at dennis@narative.co and I'd love to fill you in on all the details!
