### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shivamsinghps** [gregtuc/StockSocket#32]
on starting it is just giving message "StockSocket has opened a WebSocket Connection with Yahoo." else the callback is not getting executed

**Comment by gregtuc** [comment]
@shivamsinghps Market is closed on weekends, try entering a cryptocurrency (such as ETH-USD which is ticking 24/7). Does it still not work?

**Comment by shivamsinghps** [comment]
@gregtuc  it is working when the data is getting updated but it should at least provide the close time data too. Right? 
or
at least a flag that market is closed.

**Comment by gregtuc** [comment]
> @gregtuc it is working when the data is getting updated but it should at least provide the close time data too. Right? or at least a flag that market is closed.

The socket connection doesn't provide details on closing hours of exchanges nor historical data - just the live data as shown in the README. You can get historical prices and opening/closing hours of exchanges by sending a query to `https://query1.finance.yahoo.com/v10/finance/quoteSummary/<Enter-Ticker>?`, but it's possible that this could degrade performance of the module, especially if subscribed to many tickers listed on different exchanges. I'll take a look at this feature and see if it's worth implementing!
