### ISSUE TITLE
How to pull curent market data?

### ISSUE THREAD

**Issue by Archer2305** [gregtuc/StockSocket#34]
I want to pull the current data and not updates, I was wondering if this module supports this, or if I should use another module.
Thanks.

**Comment by gregtuc** [comment]
Hey there!

For pulling current market data once, you can easily send a `GET` request to `https://query1.finance.yahoo.com/v7/finance/quote?symbols=NVDA` (replace `NVDA` with the ticker name of your choice). This is more appropriate for your use case than the stocksocket module.

Alternatively, if you're looking for a great NPM module, I'd go over to https://github.com/gadicc/node-yahoo-finance2 . They have an API that will do the trick as well.

**Comment by v1k22** [comment]
Is it working only when market is open? Because I am getting Connection Time out error.

**Comment by gregtuc** [comment]
> Is it working only when market is open? Because I am getting Connection Time out error.

That is correct. If you wish to test the module while trading is closed and without timing out, I usually recommend opening a feed with cryptocurrencies as they are open 24/7 365. Try `ETH-USD` or `BTC-USD`.
