### ISSUE TITLE
Is there a way to receive the last price of a stock when the stock market is closed?

### ISSUE THREAD

**Issue by yuvron** [gregtuc/StockSocket#37]
If not, is something like this planned?

**Comment by arch-btw** [comment]
It seems to sporadically work in the after hours. For example, right now it's after hours and it's fetching the SPY ticker.

**Comment by gregtuc** [comment]
@arch-btw 
Hey! I see that you had posted this comment July 6th at 7:39PM ET. From what I see, SPY is a NASDAQ listed ETF, and NASDAQ Post-Market hours continue until 8:00PM ET - unless I'm mistaken, that you were still receiving data means the module was working as it should.

@yuvron 
This module can only deliver what is received from Yahoo itself. This request would be far more complex in practice than it sounds, as I'd need to:
* Query Yahoo's unofficial API for the last stock price
* Fetch and store both market hours and holiday dates for every single Yahoo-listed market to recognize when it's closed
* Periodically search each market for changes to holidays/hours.
* Periodically search for newly listed or delisted markets.

It's possible I've overlooked an easier route, however. Let me know, I'm really open to discussion on the topic!
